### ISSUE TITLE
Integrate with Horizon

### ISSUE THREAD

**Issue by amsaha** [CiscoZeus/don#18]
Lets look at https://github.com/CiscoSystems/AVOS and see how that has been done and whether we can do this in a similar fashion. This has been done by @lexholden, one of our very own :-)

**Comment by amsaha** [comment]
Related to issue #7

**Comment by ddutta** [comment]
if we can also put it in stack forge it will be gr8

On Sat, Feb 27, 2016 at 11:44 PM, Amit Saha <notifications@github.com>
wrote:

> Related to issue #7 <https://github.com/CiscoZeus/don/issues/7>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CiscoZeus/don/issues/18#issuecomment-189816472>.
>



-- 
-Debo~

**Comment by amsaha** [comment]
:+1:  See issue #9  :-)

**Comment by amsaha** [comment]
Major part done via pull #27. Readme update still pending.

**Comment by amsaha** [comment]
@Ramaraja. Can you update screenshot in README so that it has the new UI (Horizon integrated)? The DON link on the left should be visible in all the snapshots. We can then close this issue.

**Comment by amsaha** [comment]
Closed via pull https://github.com/CiscoZeus/don/pull/44
