### ISSUE TITLE
DON installation using setuptools

### ISSUE THREAD

**Issue by Ramaraja** [CiscoZeus/don#28]
As of now copying the source to horizon directory is required. Need to implement using pbr.

**Comment by amsaha** [comment]
@Ramaraja I am a bit unclear about this. What is pbr? Is there any documentation from openstack/horizon regarding this?

**Comment by Ramaraja** [comment]
My idea is to use setup.py for DON plugin install for horizon.
So I thought of trying this stuff. http://docs.openstack.org/developer/pbr/

**Comment by amsaha** [comment]
I do not know anything about this. So go ahead. Just make sure we don't spend too much time on this :-)

**Comment by Ramaraja** [comment]
Ansible can be used for automating installation.

**Comment by amsaha** [comment]
Fixed via pull #52
